### ISSUE TITLE
Snapshot not including entire screen even though I set the resolution very large

### ISSUE THREAD

**Issue by JasonFairchild** [uktrade/cypress-image-diff#100]
This plugin is only taking a screenshot of about a 1000px square section of the top left of the screen, which is a small portion of this long form I'm trying out (needs about 4000px height to render all of it without a scrollbar). Has anyone else noticed this? I'm setting the viewport like this and when I run the test, it displays with this viewport in the browser, but the snapshot command always only gets a fraction. I've also tried cy.compareSnapshot and cy.root().compareSnapshot... Is it obvious I'm doing something wrong? I'm doing this in a component test, btw.

![image](https://user-images.githubusercontent.com/56280950/186026470-50c88230-9974-4048-a095-d20f093e771a.png)

**Comment by JasonFairchild** [comment]
This seems kind of wild. I just tried another long (large height) component, doing the same thing as the example test I showed, and it did work to do the scrolling behavior and captured the whole screen. So I guess there is some difference between them, but I have no idea what. The component that isn't working is a higher level component that uses the component that did work as I'd expect...

**Comment by Jamesking56** [comment]
Yeah I got this same behaviour, won't go wider than 1000px

**Comment by Jamesking56** [comment]
I've just managed to get it to do a 1280x800 image by setting `viewportWidth` and `viewportHeight` in `cypress.config.js`.
