### ISSUE TITLE
How to skip Image difference errors

### ISSUE THREAD

**Issue by 18202izm** [uktrade/cypress-image-diff#101]
Is there a way to skip `Error: Image difference greater than threshold` errors  with this plugin?

The cypress-image-snapshot plugin provides this option.
[https://github.com/jaredpalmer/cypress-image-snapshot](url)
<img width="640" alt="スクリーンショット 2022-08-29 152505" src="https://user-images.githubusercontent.com/112163147/187136412-0a6dcaa4-825a-433a-93f8-2cb1fa1e5c5d.png">

Thank you in advance.

**Comment by Terence625** [comment]
hi, @18202izm , I'm also looking for feature, do you have any solutions, thanks

**Comment by wojciech-aniol** [comment]
I am also facing this problem. It would be great to be able to preview all diff images, not just the first one that fails the test. Now if I want to update the screenshots (only the failed ones) I need to run the test multiple times and update them one by one
