### ISSUE TITLE
snapshot testing for component testing

### ISSUE THREAD

**Issue by oguzhantx** [uktrade/cypress-image-diff#102]
Is it possible to get snapshot testing working for component testing? on the install documents, it is mentioned that **where {scheme} defaults to e2e** 
**// cypress/support/index.js for Cypress versions below 10
// cypress/support/{scheme}.js for Cypress versions 10 and above, where {scheme} defaults to e2e
require('./commands')**
is it possible to overwrite this **{scheme}** so it looks into component.js file for component testing as well? 

When I configure the framework with component testing this is the error I am getting. 
<img width="1074" alt="image" src="https://user-images.githubusercontent.com/94402055/187254724-547f39ac-8d5f-4f74-adde-a317fa122c82.png">

I tried to add compareSnapshotCommand() as a 
Cypress.Commands.add('compareSnapshotCommand', compareSnapshotCommand());
but that did not work either.

**Comment by JasonFairchild** [comment]
I have this plugin working with component testing and Cypress version 10. Which version are you using? I don't think I had to deal with this 'scheme' you talk about at all. I just added the relevant setup to the component property of the config. So my cypress.config.js:
```
const { defineConfig } = require('cypress');
const getCompareSnapshotsPlugin = require('cypress-image-diff-js/dist/plugin');

module.exports = defineConfig({
  component: {
    devServer: {
      framework: 'next',
      bundler: 'webpack',
    },
    setupNodeEvents(on, config) {
      getCompareSnapshotsPlugin(on, config);
    },
  },
});
```
Then these lines in a cypress/support/component.js just work:
```
const compareSnapshotCommand = require('cypress-image-diff-js/dist/command');

compareSnapshotCommand();

after(() => {
  cy.task('generateReport');
});
```
If you do both E2E and component testing in the same repo, then I imagine setup is slightly different, but probably not much more then just having an 'e2e' property in the config alongside the component one.

**Comment by oguzhantx** [comment]
@JasonFairchild your config seems to be working. Thanks
