### ISSUE TITLE
Image-diff result is 0.0 even there is a different element?

### ISSUE THREAD

**Issue by uhlstefa** [uktrade/cypress-image-diff#105]
Hi all,
i am new to cypress and this package and want to use it for ui testing. So far, the image-diff reacts correct, when i have a complete different page. But when i have same page, but only a different button it says failure treshhold 0.0.
Can the tool detect even those small changes?
And what information do you need to support in here?
![compare not working](https://user-images.githubusercontent.com/104195810/189334855-d8dac43f-6e9d-42b4-af20-5dff988d4844.jpg)
Hint: The elements are inside an iFrame. Could that be an issue?

**Comment by PippoRaimondi** [comment]
hey, it should detect any pixel difference for a given page or element... can you share the code that resulted in a no pixel difference? I suspect you are taking screenshots of some other element causing it not to fail?

**Comment by PippoRaimondi** [comment]
closing this as it doesn't seem to be an issue.

**Comment by uhlstefa** [comment]
Cause of sickness i wasn't able to answer earlier. I still have the problem. 
```
  cy.compareSnapshot('Button Tertiary', {
             capture: 'viewport',
             errorThreshold: 0.0,
             overwrite : true
        });
```

**Comment by uhlstefa** [comment]
@PippoRaimondi Could you pls support here again? Thx
