### ISSUE TITLE
How to update Snapshots of specific test case instead of all test?

### ISSUE THREAD

**Issue by 787681277** [uktrade/cypress-image-diff#107]
No need to update the base image files for all tests.In actual scenario, just need to re-generate baseline image for specific test case

**Comment by PippoRaimondi** [comment]
This is something we could improve! I am marking this as a good next feature!

**Comment by Rahulpar** [comment]
@PippoRaimondi , thanks for putting this project together. Is the requirement for this enhancement to accept a list of files to be copied from "comparison" folder into (if a diff found for the same list of files) "baseline" folder ?

Can one of you help me to understand, how to run this command from CLI ?
I tried these options, and they are not working. 
cypress run --spec "cypress/e2e/visual-capture.cy.js" --update (Try 1)
Also
cypress-image-diff -u (Try 2 - as an executable in Windows) 
Apologies for hacking the thread.
