### ISSUE TITLE
Cypress 10 generates screenshots outside of folder-scructure-test folder

### ISSUE THREAD

**Issue by evgenysyrkashev** [uktrade/cypress-image-diff#112]
From the list of Cypress 10.0.0 [breaking changes](https://docs.cypress.io/guides/references/changelog#10-0-0): 

> Generated screenshots and videos will still be created inside their respective folders (screenshotsFolder, videosFolder). However, the paths of generated files inside those folders will be stripped of any common ancestor paths shared between spec files found by the specPattern option and may no longer be deterministic. Addressed in [#19319](https://github.com/cypress-io/cypress/pull/19319).

Steps to reproduce:
 - update Cypress to 10.8.0 in package.json;
 - run `npm install`;
 - run `cypress open` and migrate config files;
 - run `npm run test:e2e`;
 - observe that `folder-structure.cy-wholePage.png` is generated outside of `folder-structure-test` folder.

**Comment by PippoRaimondi** [comment]
Thanks a lot for pointing this out, I will have a look and provide a fix as soon as I can!

**Comment by PippoRaimondi** [comment]
Ok, I've been working to try to fix this and there is no non-hacky way of doing this..

When taking screenshots, cypress would store and create folder structures that matched your spec structure based on the below information:

```
{
  name: 'folder-structure-test/folder-structure-spec-wholePage',
  specName: 'folder-structure-test/folder-structure-spec.js',
  path: '/Users/filipporaimondi/code/cypress-image-diff/cypress/screenshots/folder-structure-test/folder-structure-spec.js/folder-structure-test/folder-structure-spec-wholePage (1).png',
  ...
}
```

Now this same object is missing the `specName` and flattens any folder structure, hence it puts all screenshots in the same folder... so not only they stopped replicating the spec folder structure in the screenshot creation but also removed any information that would allow us to do it ourselves in a `after:screenshot` hook:

```
{
  name: 'folder-structure.cy-wholePage',
  path: '/Users/filipporaimondi/code/cypress-image-diff/cypress/screenshots/folder-structure.cy-wholePage (1).png',
  ...
}
```

There are ways of course to handle this, but it would require quite a significant amount of rework and it would feel extremely hacky and for sure it wouldn't work for all cases... given it would rely on knowing a folder structure and this folder structure can be changed by cypress `integrationFolder` configurable path...

Unfortunately for now there will be a Cypress 10.x limitation...

I will be opening a ticket against cypress, which hopefully they can fix quickly, given I won't ask them to revert this breaking change, but just simply include `specName` that contains the folder structure so we can create it ourselves on a `after:screenshot` hook... once they provide this property again I can easily update this package to support complex folder structure again.

**Comment by uhlstefa** [comment]
Any update on this? I had the same issue with headless mode and therefore my tests break the CI jobs. Any workaround there so far?
