### ISSUE TITLE
Normalize screen pixel densities

### ISSUE THREAD

**Issue by jkjustjoshing** [uktrade/cypress-image-diff#115]
When I collect snapshots using `cypress run`, the screenshots collected are collected at a default pixel density. However, when I collect snapshots using `cypress open` on my MacBook, the screenshots collected are at double pixel density.

Is there a way to standardize this? Otherwise, when I run my tests using `cypress open` they always fail because the comparison images are twice as wide as the baseline images that were generated with `cypress run`.

**Comment by Lyokolux** [comment]
I am looking for this too because we are using MacBooks at my company but I would integrate it in the CI too.

**Comment by Lyokolux** [comment]
Here is a visual regression plugin that does it: https://github.com/meinaart/cypress-plugin-snapshots#make-changes-to-default-configuration

**Comment by nmkataoka** [comment]
Thanks @Lyokolux , the logic there is pretty simple: https://github.com/meinaart/cypress-plugin-snapshots/blob/master/src/tasks/matchImageSnapshot.js#L32. I'll try it out.

**Comment by BatyrSeven** [comment]
You can set scale factor for Chrome in launch options:

```
// cypress.config.js
setupNodeEvents(on, config) {
  getCompareSnapshotsPlugin(on, config)
  
  on('before:browser:launch', (browser, launchOptions) => {
    if (browser.name === 'chrome') {
      // force screen to be non-retina
      launchOptions.args.push('--force-device-scale-factor=1')
    }

    return launchOptions
  })
}
```

**Comment by Lyokolux** [comment]
> You can set scale factor for Chrome in launch options:
> 
> ```
> // cypress.config.js
> setupNodeEvents(on, config) {
>   getCompareSnapshotsPlugin(on, config)
>   
>   on('before:browser:launch', (browser, launchOptions) => {
>     if (browser.name === 'chrome') {
>       // force screen to be non-retina
>       launchOptions.args.push('--force-device-scale-factor=1')
>     }
> 
>     return launchOptions
>   })
> }
> ```

This is great workaround, but it does not provide a solution for every browsers. I checked for Firefox and didn't find a solution.
Maybe we can add this workaround on the README after the warning though.

**Comment by admapop** [comment]
> You can set scale factor for Chrome in launch options:
> 
> ```
> // cypress.config.js
> setupNodeEvents(on, config) {
>   getCompareSnapshotsPlugin(on, config)
>   
>   on('before:browser:launch', (browser, launchOptions) => {
>     if (browser.name === 'chrome') {
>       // force screen to be non-retina
>       launchOptions.args.push('--force-device-scale-factor=1')
>     }
> 
>     return launchOptions
>   })
> }
> ```

Really good workaround, it's worked in my case!
Thanks!
