### ISSUE TITLE
Image comparision question

### ISSUE THREAD

**Issue by ssauriera** [uktrade/cypress-image-diff#117]
I'm using this pluguin to compare two divs. The only difference it's the background color from #5291dd to #5291aa as you can see in the images attached
Baseline:
![testing spec cy ts-selected item](https://user-images.githubusercontent.com/5089486/193000286-7080dedf-2e6e-4cd1-ad23-eeb09df48f46.png)

Comparision:
![testing spec cy ts-selected item](https://user-images.githubusercontent.com/5089486/192999886-ea23c75f-10d5-4778-b63c-354d8bbd5523.png)

I would like to understand why this test doesn't fail. 

Thanks in advance

**Comment by uhlstefa** [comment]
I have a similar issue. I have 3 different button styles. But the test never fails no matter which button image is use as comparison. It detecs when i am on a complete different page, but not when only the button stype is different

**Comment by ssauriera** [comment]
@PippoRaimondi I have run pixelmatch manually with the two images generated. If I run with a threshold of 0 pixelmatch fails, but if I run with 0.1 not fail. 

Looking at your code, you run pixelmatch with 0.1 by default instead of the threshold we configure on the compareSnapshot snapshot command.

This code's from your pluguin.js

![image](https://user-images.githubusercontent.com/5089486/208046540-8e46b4ea-585e-42f0-aca4-ab13bb33712b.png)

I tested changing this threshold on the npm package in my projects, and the test fail as expected.

**Comment by kien-ht** [comment]
We have merged the pull request #165 that opens pixelmatch options to users, which will help you resolve this issue.
