### ISSUE TITLE
question about options

### ISSUE THREAD

**Issue by jradom** [uktrade/cypress-image-diff#12]
Please, let me know if I can configure density, threshold, mask/exclusion areas, etc?

Thanks

Jeff

**Comment by jradom** [comment]
Please clarify how to assert result in case of pass or failure

**Comment by jradom** [comment]
I've tried to run your tool and I use Cypress/Typescript and got this
![image](https://user-images.githubusercontent.com/20550461/99354020-834d9700-285a-11eb-8afb-96b0c3982ce0.png)
![image](https://user-images.githubusercontent.com/20550461/99354019-834d9700-285a-11eb-9867-2cd031a1729b.png)
Please help

**Comment by PippoRaimondi** [comment]
@jradom have you followed these steps prior to writing the tests?

https://github.com/uktrade/cypress-image-diff/blob/main/docs/Cypress%20integration.md

**Comment by PippoRaimondi** [comment]
Will close this issue with the assumption that not all setup steps were followed.

**Comment by jradom** [comment]
I’m not sure what do you mean. I’m away from my laptop and will check again if your tool work as expected

**Comment by PippoRaimondi** [comment]
> Please, let me know if I can configure density, threshold, mask/exclusion areas, etc?
> 
> Thanks
> 
> Jeff

Threshold/density can be configured per test... I might introduce a global but for now there isn't a need as usually there are only a couple of test scenarios that you would want to change these configurations hence the configurable option on test level.

The below feature will take care of masking areas which is pretty much done by hiding elements/divs that are generated dynamically by system time for example.

https://github.com/uktrade/cypress-image-diff/issues/7

**Comment by jradom** [comment]
Sorry, I had looked inside #7 link but didn't understand how to exclude certain elements from comparison.  Please, clarify

Thanks

Jeff
