### ISSUE TITLE
Unable to accurately update baseline image

### ISSUE THREAD

**Issue by jwangyangls** [uktrade/cypress-image-diff#120]
Unable to accurately update baseline image

I generated two pictures in the baseline through the code, img1 and img2, and the same two pictures in the compoarision. At this time, the logic of img2 was deleted in my code, and after using the cli update (cypress run --component && cypress -image-diff.js -u) img2 in baseline is not automatically deleted

**Comment by PippoRaimondi** [comment]
deletion of baselines are still manual unfortunately... although this is a feature that could definitely be introduced!

**Comment by jwangyangls** [comment]
Oh I think I might just use the container to run this way
