### ISSUE TITLE
different resolution between cypress run && cypress open cli

### ISSUE THREAD

**Issue by binvb** [uktrade/cypress-image-diff#122]
config:  
    "test": "DEBUG=code-coverage cypress open --component --browser chrome",
    "test:force-update-baseLine": "DEBUG=code-coverage cypress open --component --browser chrome && cypress -image-diff.js -u",
    "test:commit": "cypress run --component --browser chrome && npx nyc report"

my step: 
1、npm run test:force-update-baseLine;  
2、npm run test;  
it can pass the image compare test, but if i run: test:commit, it  will report err:  
Error: Image difference greater than threshold: 0

here's two images compare, seem's different resolution:  
<img width="720" alt="image" src="https://user-images.githubusercontent.com/18115907/197729964-6ada86aa-e63e-4fe0-a79a-f1f24330d3a8.png">

thank you very much

**Comment by revoyrm** [comment]
We have the same issue. We also see this resolution issue when running it in open on different monitors. Which means it will pass for one engineer and not another.

**Comment by PippoRaimondi** [comment]
Hello, thanks for raising this. In the documentation the following is stated:

```
Please notice
Be aware that despite forcing a screenshot resolution to a particular height and width for a test, if this test is run on different computers (i.e a 13" Mac vs PC attached to a 30" monitor), the results will be different. So it's extremely important that you standardize where the tests will run, both locally and CI.

One way to handle this is by running it with docker container. This project tests use a docker container to run the tests so it could be used as an example.
```

So basically, you need to run the tests on a consistent way for tests to be consistent (and unfortunately that means headless vs cypress gui as well).

Closing as it's a non issue.
