### ISSUE TITLE
Passing options for the cypress screenshot command

### ISSUE THREAD

**Issue by JasonFairchild** [uktrade/cypress-image-diff#123]
Is this not possible? It doesn't appear to be from the code, but I don't see why it could not be. I'd like to be able to clip the screenshot before it is compared. https://docs.cypress.io/api/commands/screenshot#Clip

I may even open a PR to add this capability myself, but has anyone else tried or thought about it and know it is much more difficult than it may look? I think I would basically just add another parameter to the custom command and pass that object along to the screenshot command, so it would just need to follow cypress' docs otherwise. What else would need to be accounted for? I guess it might be tricky to ensure it is backwards compatible and also works with or without retryOptions..?

Thanks for any feedback.

**Comment by PippoRaimondi** [comment]
We can provide screenshot options, but at global level not individually:

I.E

in `support/commands` file you can do the following:

```
compareSnapshotCommand({ disableTimersAndAnimations: false, clip: { x: 20, y: 20, width: 400, height: 300 } });
```

Although this would mean every screenshot would have this configuration...

I will mark this is a good next enhancement!

**Comment by JasonFairchild** [comment]
Yeah, I couldn't do this clip option for all screenshots, or at least it would be really hacky/tedious to get it to work for every other situation.

To be clear, the enhancement you mean is to allow for passing the options on an individual compareSnapshot instance basis, right? The reason I want to do this clipping is actually probably because some odd cypress component testing specific bug, or possibly even a chrome bug, so maybe it would be more ideal to pursue that to resolve my case. But I do still think that in general being able to pass screenshot options would be a nice enhancement.

**Comment by PippoRaimondi** [comment]
Yes, this enhancement would be to add the options to individual compareSnapshot commands!
