### ISSUE TITLE
Question: get report from CI

### ISSUE THREAD

**Issue by Maksim631** [uktrade/cypress-image-diff#126]
Hi, I'm trying to add image comparison into my github action. I wanna get html report to be able to analyse failed cases. Are there any ways to download html report from github action? Maybe its possible to send report to email.
Also I tried to use cypress dashboard, but I also couldn't see report or even diff snapshots there.

**Comment by PippoRaimondi** [comment]
Make sure to follow the steps for report setup:

https://github.com/uktrade/cypress-image-diff/blob/main/docs/Reporting.md

As long as you follow these steps the report with image comparison will be generated... once you do that, make sure to save the html report artifact to your github action so you can later on download it.

**Comment by Maksim631** [comment]
Thanks!
