### ISSUE TITLE
Can i display report on Gitlab CI

### ISSUE THREAD

**Issue by Strezzo06** [uktrade/cypress-image-diff#128]
Anyone know? how to display report on Gitlab CI

**Comment by PippoRaimondi** [comment]
Yes, you can display the report generated by this plugin by saving it to artifacts (html report) and even deploy it so it can be accessed externally... you will need to follow gitlab's [documentation](https://docs.gitlab.com/ee/ci/pipelines/job_artifacts.html) for that..

To generate the report for this plugin, follow this [documentation](https://github.com/uktrade/cypress-image-diff/blob/main/docs/Reporting.md)
