### ISSUE TITLE
Add cypress 11 and 12 as valid peer dependencies

### ISSUE THREAD

**Issue by jfairchild-aumni** [uktrade/cypress-image-diff#129]
Cypress 12 changes how custom commands are handled

**Comment by PippoRaimondi** [comment]
currently on a backpack trip but will sort out soon!

**Comment by nischi** [comment]
This would be awesome.

**Comment by web-dave** [comment]
Any progress here?

**Comment by tannera** [comment]
> Any progress here?

This was fixed in: https://github.com/uktrade/cypress-image-diff/releases/tag/v1.23.0

We can close this issue.
