### ISSUE TITLE
no diff image available

### ISSUE THREAD

**Issue by uhlstefa** [uktrade/cypress-image-diff#133]
Hi,
I want to try this package for visual testing.
I have cypress 10.10 installed atm (also tried with cypress 9.0.0 as it used this before, but no help). 

I followed the instructions and it shows me a difference between the screenshots:
logFAIL: Image difference percentage 0.2244623205202453

bit the folder "diff" is always empty... So I need support to get it to work.
![14-12-_2022_01-06-05](https://user-images.githubusercontent.com/104195810/207472025-99b7618a-edf6-4ec9-ad16-e39e5388af32.jpg)

Also: Why is the chrome windows when using the plugin always so small?

![why so small window](https://user-images.githubusercontent.com/104195810/207473050-4a130ecf-6505-482c-9e33-99dd28b031a7.jpg)

**Comment by PippoRaimondi** [comment]
Hi, how did you run it? Have you ran it using `cypress run`?

**Comment by PippoRaimondi** [comment]
read [this section](https://github.com/uktrade/cypress-image-diff#force-resolution-size) of the documentation for some viewport info..

I invite you to read the rest of the documentation in general to get familiar what this plugin can do for you...

[also this bit](https://github.com/uktrade/cypress-image-diff#please-notice) for consistency in your test results
