### ISSUE TITLE
Add description to change the default threshold from 0 to the README

### ISSUE THREAD

**Issue by Mike685123** [uktrade/cypress-image-diff#142]
Hello,
I would like to know how to change the default threshold from 0. Thanks

**Comment by tamasmagyar** [comment]
I think there is no global option to change the default 0 value. [You can change it for each compareSnapshot command though.](https://github.com/uktrade/cypress-image-diff#take-screenshot-and-compare-the-whole-page:~:text=cy.compareSnapshot(%27home%2Dpage%2Dwith%2Dthreshold%27%2C%200.2))
