### ISSUE TITLE
Not able to use cy.compareSnapshot command

### ISSUE THREAD

**Issue by ahplaza** [uktrade/cypress-image-diff#145]
Hello, after following the [documentation](https://github.com/uktrade/cypress-image-diff/blob/main/docs/Cypress%20integration.md) to integrate the tool for Cypress it still says that `'does not exist on type 'cy & CyEventEmitter'`.

I saw that a similar problem was reported [here](https://github.com/uktrade/cypress-image-diff/issues/23), but after closed it was reported that it still has problems.

I'm using Cypress version 12.0.0 with .ts files and I don't have Cucumber, so I think it's something else.

In this blog: https://reflect.run/articles/comparing-screenshots-in-cypress/ it says that you have to include code at commands file. Tried also that but still not working.

**Comment by mrMojo1996** [comment]
+1

**Comment by bakasmarius** [comment]
Same here. When I am importing `import { compareSnapshotCommand } from 'cypress-image-diff-js/dist/command'` in `cypress\support\e2e.ts`, I get the following warning/suggestion:
```
Try `npm i --save-dev @types/cypress-image-diff-js` if it exists or add a new declaration (.d.ts) file containing `declare module 'cypress-image-diff-js/dist/command';` ts(7016)
```

The screenshot tests work fine BTW, it's just that TypeScript is complaining about `cy.compareSnapshot()`

**Comment by tamasmagyar** [comment]
Can you try adding the lines below to your `cypress/support/e2e.ts` file?

```
import compareSnapshotCommand from 'cypress-image-diff-js/dist/command';
import { RecurseDefaults } from 'cypress-recurse';
import '@testing-library/cypress/add-commands';

declare global {
  namespace Cypress {
    interface Chainable {
      compareSnapshot(
        name: string,
        testThreshold?: number,
        retryOptions?: Partial<typeof RecurseDefaults>,
      ): Chainable<Element>;
    }
  }
}
compareSnapshotCommand();
```

**Comment by bakasmarius** [comment]
> Can you try adding the lines below to your `cypress/support/e2e.ts` file? You might have to install cypress-recurse package as well.
> 
> ```
> import compareSnapshotCommand from 'cypress-image-diff-js/dist/command';
> import { RecurseDefaults } from 'cypress-recurse';
> 
> declare global {
>   namespace Cypress {
>     interface Chainable {
>       compareSnapshot(
>         name: string,
>         testThreshold?: number,
>         retryOptions?: Partial<typeof RecurseDefaults>,
>       ): Chainable<Element>;
>     }
>   }
> }
> compareSnapshotCommand();
> ```

Well, TypeScript does not complain in VSCode anymore, but the tests also do not work anymore 😄 
![image](https://github.com/uktrade/cypress-image-diff/assets/22072884/d323ace4-0c11-4583-81d7-e37603119edf)

**Comment by bakasmarius** [comment]
> Can you try adding the lines below to your `cypress/support/e2e.ts` file? You might have to install cypress-recurse package as well.
> 
> ```
> import compareSnapshotCommand from 'cypress-image-diff-js/dist/command';
> import { RecurseDefaults } from 'cypress-recurse';
> 
> declare global {
>   namespace Cypress {
>     interface Chainable {
>       compareSnapshot(
>         name: string,
>         testThreshold?: number,
>         retryOptions?: Partial<typeof RecurseDefaults>,
>       ): Chainable<Element>;
>     }
>   }
> }
> compareSnapshotCommand();
> ```

Thanks, looks like it helped 😉

**Comment by PippoRaimondi** [comment]
We will be sorting out a few of these issues shortly with a new release of the package. I will leave this issue opened so it could be tracked.

**Comment by biswabose1992** [comment]
Do we have any update onthe release for this @PippoRaimondi
