### ISSUE TITLE
Feature Request: Produce diff for passed tests as well

### ISSUE THREAD

**Issue by aghArdeshir** [uktrade/cypress-image-diff#149]
Hello. And thanks for this awesome library.

I read through the docs and could not find a way to ask this lib to produce diff and reports even for passed tests.

I can see the reasons why it does not (performance reasons mostly), but in my case, if I set the threshold to 10% and a test generates 9% threshold and passed, I still would like to check out that 9% occasionally.

![image](https://github.com/uktrade/cypress-image-diff/assets/5755214/b9ff6c43-477b-4ca8-a84d-9f0d7afaf74b)

It could be an option `produceDiffOnPassedTests: true` or maybe even better `diffProduceThreshold: 5%` so developers can still ignore 0-5% threshold.

**Comment by tamasmagyar** [comment]
[Based on my research comparison image is only generated upon a failure. ](https://github.com/uktrade/cypress-image-diff/blob/main/src/plugin.js#L94)

I think it would be a nice optional parameter, like the one you mentioned: `produceDiffOnPassedTests`.
