### ISSUE TITLE
Hardcoded prefix added to filenames

### ISSUE THREAD

**Issue by jarretmoses** [uktrade/cypress-image-diff#15]
I am not sure if this is intentional or not but as I was working with this package I noticed that if I run all my tests through the GUI from `cypress open` by clicking run all integration tests, my screenshot file names get a hardcoded prefix added to them as seen in the attached screenshot `All Integration Specs`. Is this an intention? Seems if I were to have CI errors and want to rerun locally through `cypress open` to debug it would be best to standardize the file naming convention no matter how the test is run especially since running all tests through `cypress run` follows the same file naming convention as running a singular suite through cypress open. Granted I know I'd most likely just run a singular suite to debug but still feel the naming convention should stay the same.

<img width="330" alt="Screen Shot 2020-12-05 at 11 18 17 AM" src="https://user-images.githubusercontent.com/4745679/101252053-0ccee700-36ec-11eb-8d41-5e831b7fd9c6.png">

**Comment by PippoRaimondi** [comment]
I see the problem here, the testname value from cypress is different depending on the test run method... I will get this fixed shortly!

**Comment by PippoRaimondi** [comment]
@jarretmoses there is a bug opened against cypress to fix this issue when running all tests:

https://github.com/cypress-io/cypress/issues/3090

if you want to run all tests you will have to stick with the `cypress run` command until the above is fixed.
