### ISSUE TITLE
Updating the baseline images via CLI doesn't work with custom rootDir

### ISSUE THREAD

**Issue by krista-prokop** [uktrade/cypress-image-diff#150]
I set a custom rootdir so my results are saved to `'C:\dashboard\cypress`:
```
	setupNodeEvents(on, config) {
			getCompareSnapshotsPlugin(on, config, {
				rootDir: 'cypress',
			})
		},
```

When i try to update baseline images via `cypress-image-diff -u` it fails because it's using the default directory:

```
Error: ENOENT: no such file or directory, scandir 'C:\dashboard\cypress-visual-screenshots\diff'
```

**Comment by PippoRaimondi** [comment]
Very good catch! I will get it fixed shortly! in the meantime, a workaround is to manually replace the images...
