### ISSUE TITLE
specify paths for baseline, comparison and diff

### ISSUE THREAD

**Issue by saw2881** [uktrade/cypress-image-diff#154]
Is there a way to provide different paths for the baseline, comparison and diff?
Here is my use case, I want to make a baseline run and store the baseline images at one specific location and the daily runs then compare against the baseline path.

**Comment by tamasmagyar** [comment]
I don't think so. It is hard-coded here: https://github.com/uktrade/cypress-image-diff/blob/main/src/config.js#L19C1-L20C1

I think it would be a nice feature to have. What do you think @PippoRaimondiDIT ? 

Happy to start implementing if this is something we would like to have implemented.

**Comment by tamasmagyar** [comment]
Also mentioned here https://github.com/uktrade/cypress-image-diff/issues/9

**Comment by tamasmagyar** [comment]
`[Baseline, comparison and diff folder share the same screenshot folder as a parent folder. ](https://github.com/uktrade/cypress-image-diff/blob/main/src/config.js#L23)`

**Comment by tamasmagyar** [comment]
[Baseline, comparison and diff folder share the same screenshot parent folder](https://github.com/uktrade/cypress-image-diff/blob/main/src/config.js#L23)
