### ISSUE TITLE
Custom cypress.config path

### ISSUE THREAD

**Issue by krista-prokop** [uktrade/cypress-image-diff#157]
Cypress allows you to place your cypress.config file anywhere. For example my config below is not in the project root but in `./cypress/cypress.config.ts`. 

```
import { defineConfig } from 'cypress'
import getCompareSnapshotsPlugin from 'cypress-image-diff-js/dist/plugin'

export default defineConfig({
	e2e: {
		baseUrl: LOCAL_APP_SERVER_URL,
		setupNodeEvents(on, config) {
			getCompareSnapshotsPlugin(on, config, {
				rootDir: SNAPSHOT_TEST_SCREENSHOTS_DIR,
			})
		},
	},
})
```

The `rootDir` directive for `cypress-image-diff` is not respected because the lib is looking for this in the project root.  It only works if I move the config file to the project root.

Is there a way to specify the location of my config file?

**Comment by kien-ht** [comment]
Specifying custom path for `cypress-image-diff.config` is unfortunately not supported. I would propose to have our own dedicated object inside `Cypress.env` like this:

```
// cypress.config.js
const { defineConfig } = require('cypress')

module.exports = defineConfig({
  env: {
    ...
    cypressImageDiff: {
       rootDir: 'foo'
    }
  },
})
```
The actual `cypress-image-diff.config` (if found in the root project) might take precedence over this `cypressImageDiff` object config. I could create a pull request for this shortly if it makes sense.

@PippoRaimondi What do you think?

**Comment by kien-ht** [comment]
Specifying custom path for `cypress-image-diff.config` is unfortunately not supported. I would propose to have `cypress-image-diff.config` file sitting default under the `rootDir`. To me, `rootDir` should dictate every file and folder that is belong to our plugin.

Or it is also possible to pass extra argument for cli, for example: `cypress-image-diff -u --config-file=customRootDir`, in which customRootDir is the directory that our plugin looks for the configuration file.

@PippoRaimondi  What do you think?
