### ISSUE TITLE
A bug of @1.27.0 TypeError: Cannot read properties of undefined (reading 'FAILURE_THRESHOLD')

### ISSUE THREAD

**Issue by natsuki-engr** [uktrade/cypress-image-diff#159]
In the version of 1.27.0, `cy.compareSnapshot` throws the following error, in case of missing the params `testThreshold` and `recurseOptions` of `cy.compareSnapshot` command.
```
 TypeError: Cannot read properties of undefined (reading 'FAILURE_THRESHOLD')
```
![image](https://github.com/uktrade/cypress-image-diff/assets/63272932/8bce367d-d4ae-4074-b55f-12bea3f2b733)

The cause of this may be this import statement in head of `src/plugin.js`.
```
import paths, { userConfig } from './config'
```
https://github.com/uktrade/cypress-image-diff/blob/a6a8c748b3169e7b92f3f33dc0a441f0ed88c21b/src/plugin.js#L13

This must be like this?
```
import { paths, userConfig } from './config'
```

**Comment by natsuki-engr** [comment]
sorry, my code(cypress.config.js) is wrong.

in `cypress.config.js`

**wrong**
```
setupNodeEvents(on, config) {
  const getCompareSnapshotsPlugin = require('cypress-image-diff-js/dist/plugin')
  getCompareSnapshotsPlugin(on, config)
},
```

**correct**
```
setupNodeEvents(on, config) {
  const getCompareSnapshotsPlugin = require('cypress-image-diff-js/dist/plugin')
  return getCompareSnapshotsPlugin(on, config)
},
```

it was missing to return result of `getCompareSnapshotsPlugin(on, config)`.

**Comment by nsteinmetz** [comment]
Hi there,

Having the similar issue with properties coming in 1.27.1

Doc says : https://github.com/uktrade/cypress-image-diff/blob/main/docs/Cypress%20integration.md

```
// Cypress v10+ with TypeScript
// cypress.config.ts
import getCompareSnapshotsPlugin from 'cypress-image-diff-js/dist/plugin';

export default defineConfig({
  e2e: {
    setupNodeEvents(on, config) {
      getCompareSnapshotsPlugin(on, config);
    },
  },
});
```

but it would not work.

By doing:

```
// Cypress v10+ with TypeScript
// cypress.config.ts
import getCompareSnapshotsPlugin from 'cypress-image-diff-js/dist/plugin';

export default defineConfig({
  e2e: {
    setupNodeEvents(on, config) {
      return getCompareSnapshotsPlugin(on, config);
    },
  },
});
```

It would work but is it the expected behaviour and should the doc be updated too ?
