### ISSUE TITLE
Modify Reports by optionally specifying a custom hbs in config file

### ISSUE THREAD

**Issue by Vaene** [uktrade/cypress-image-diff#160]
feat: Custom hbs report file

Specify a custom hbs file in config file

To make customizing reports easier, allow a custom location for a custom hbs file to be specified in the config file. Possibly something like this:
// cypress-image-diff.config.js
const config = {
  CUSTOM_REPORT: 'path/to/custom/report/custom-report-name.hbs',
};

module.exports = config;

**Comment by kien-ht** [comment]
Custom HTML report is now possible with the new `JSON_REPORT` option, please take a look at the [documentation](https://github.com/uktrade/cypress-image-diff/blob/main/docs/Reporting.md#generate-custom-html-report).
