### ISSUE TITLE
Random failure of a test with captured image of the wrong size

### ISSUE THREAD

**Issue by fperie** [uktrade/cypress-image-diff#164]
Hello,

Randomly, on the first test after loading a static page (which contains the possible styles for my buttons), the test can fail.

On my website, my buttons have a size of 125px * 40px.

I have no specific configuration; I have left the plugin's default configuration (so the threshold is set to 0, no retries).

My test is very simple. Essentially, I do:

```typescript
cy.visit('http://.....');
cy.get('#myButton').compareSnapshot('myButton');
```

Randomly, my test fails because the snapshot taken at the beginning of the test can be only 122px * 40px (the image is cropped). The difference threshold is then greater than 0, and the test fails.

Where does the problem originate from?
What can I do?

It's unfortunate not to be able to have reproducible tests in CI.

By adding a cypress-image-diff.config.ts file, I don't reproduce the issue, but this solution seems less robust to me.

Here is the content of the cypress-image-diff.config.ts file:

```typescript
const config = {
    FAILURE_THRESHOLD: 0,
    RETRY_OPTIONS: {
        limit: 2, // max number of iterations
        delay: 500, // delay before the next iteration, ms
        log: true
    }
};

module.exports = config;
```

Below is the content of my `package.json` file:
```json
{
  "scripts": {
    "test:ui:open": "cypress open --config-file cypress.config.ts",
    "test:ui:run": "cypress run --config-file cypress.config.ts"
  },
  "devDependencies": {
    "cypress": "12.17.4",
    "cypress-image-diff-js": "1.27.1",
    "cypress-real-events": "1.10.0",
    "typescript": "~4.8.4"
  }
}
```

Below is an image of the report detailing the infamous random error :
![cypress-bug](https://github.com/uktrade/cypress-image-diff/assets/1265267/20680cf0-1713-4424-84cd-e707c7728ced)

Thank you for your assistance,
Fabien

**Comment by PippoRaimondi** [comment]
Hello, a big part of visual testing comes to infrastructure, meaning where you run the tests...

as part of this project, we use docker containers to run tests locally and in CI ensuring both runs run in the exact same machinery... below is a note with a bit more detail:

https://github.com/uktrade/cypress-image-diff#please-notice

as far as I can tell the tool is doing the right thing, it's just being run in most likely different machines/VMs setups... hope this helps.

**Comment by fperie** [comment]
Hello @PippoRaimondi,
all tests are executed in my computer, it's not a problem with different infrastructure.

**Comment by PippoRaimondi** [comment]
> By adding a cypress-image-diff.config.ts file, I don't reproduce the issue, but this solution seems less robust to me.

Can you confirm that if the `cypress-image-diff.config.ts` is configured with the values present in the initial thread post, you can't see the problem occurring?
