### ISSUE TITLE
Issue with peerdependency updating Cypress to V13.1.0

### ISSUE THREAD

**Issue by MelvinBaaijAviva** [uktrade/cypress-image-diff#167]
I am using cypress-image-diff-js (V1.28.0) for a project. I am trying to install / update Cypress from V12.17.4 to 13.1. 0 , but this is not possible due to a non resolvable peer dependency used in cypress-image-diff-js for Cypress. 

Could not resolve dependency:
npm ERR! peer cypress@"^9.6.1 || ^10 || ^11 || ^12" from cypress-image-diff-js@1.26.0

**Comment by ElzouW** [comment]
Hello, 

I have the same dependency issue with these versions:

- cypress@13.0.0
- cypress-image-diff-js@1.28.0

I really love cypress-image-diff so I hope it will be fixed soon! 😊

**Comment by PippoRaimondi** [comment]
@ElzouW @MelvinBaaijAviva we'll work on sorting it out! we have a growing team to support this plugin @kien-ht @tamasmagyar
