### ISSUE TITLE
How to disable css animations and transitons using this plugin 

### ISSUE THREAD

**Issue by biswabose1992** [uktrade/cypress-image-diff#171]
While executing my test on pre-prod env image moves to the right which is not ideal. I have googled to find ways to disable animation or trasntion but bit clueless in terms of how to do this in cypress tests.

Can someone hep if anyone has encountered this problem? 

Also can we have any enhaancement to disable the animation/transition completely which taking screenshots using this plugin

![dealCompletedPageTest ts-desktop deals completed home-page](https://github.com/uktrade/cypress-image-diff/assets/127774065/898acfa1-d91b-4cdf-90e8-48a82c302f8f)

**Comment by kien-ht** [comment]
Hi. What didn't work for you? We internally use `Cypress.screenshot` command to take screenshots. Seems like `disableTimersAndAnimations` is what you need, [Cypress screenshot configuration](https://docs.cypress.io/api/commands/screenshot)

At the moment, there is only configuration at the global level for this option in our plugin, however there will be an enhancement soon. 

```
// Cypress v10+
// cypress/support/{scheme}.js, where {scheme} defaults to e2e
const compareSnapshotCommand = require('cypress-image-diff-js/dist/command');
compareSnapshotCommand({ disableTimersAndAnimations: false });
```
