### ISSUE TITLE
Configure reporting assets location

### ISSUE THREAD

**Issue by naturedamends** [uktrade/cypress-image-diff#173]
Whats the plan for this? I noticed there was an announcement for doing reporting configuration. Is there any open issues, or feature plans? 

Happy do a PR if its not massive and i've got a little direction

**Comment by kien-ht** [comment]
Hi. Are you referring to the custom report configuration? It was merged in this pull request #166 , [read the docs](https://github.com/uktrade/cypress-image-diff/blob/main/docs/Reporting.md#generate-custom-html-report)

If you've got any ideas, please come forward.
