### ISSUE TITLE
HTML report generation cypress-mochawesome-reporter plugin broken when updating cypress-image-diff-js from V1.26.0 to V1.30.1

### ISSUE THREAD

**Issue by MelvinBaaijAviva** [uktrade/cypress-image-diff#177]
Hi, 

I am experiencing a problem. My cypress-mochawesome-reporter plugin (V3.6.0) does not generate html reports after updating cypress-image-diff-js from V1.26.0 to V1.30.1 (using Typescript and Cypress 12.7.4 ).
I am not using a seperate cypress-image-diff.config.js

**Comment by kien-ht** [comment]
Hi. Can you share the code where you configured `cypress-mochawesome-reporter` and our plugin please?

**Comment by kien-ht** [comment]
I assume this is the Cypress multiple `on` events issue, https://github.com/cypress-io/cypress/issues/5240.
I have taken a look at the `cypress-mochawesome-reporter` codebase, and interestingly they also use the `after:run` hook in `setupNodeEvents`, and so does our plugin. If we register the same event more than once, Cypress will only apply the handler of the last one. We have one issue related to this, https://github.com/uktrade/cypress-image-diff/issues/172#issuecomment-1714066937.

You could wrap `on` function before passing it to any plugins and forward all events. I believe there are solutions for this and [cypress-plugin-init](https://github.com/elaichenkov/cypress-plugin-init) is one of them.

**Comment by MelvinBaaijAviva** [comment]
> I assume this is the Cypress multiple `on` events issue, [cypress-io/cypress#5240](https://github.com/cypress-io/cypress/issues/5240). I have taken a look at the `cypress-mochawesome-reporter` codebase, and interestingly they also use the `after:run` hook, and so does our plugin. If we register the same event more than once, Cypress will only apply the handler of the last one. We have one issue related to this, [#172 (comment)](https://github.com/uktrade/cypress-image-diff/issues/172#issuecomment-1714066937).
> 
> You could wrap the `on` function before passing it to any plugins and forward all events. I believe there are solutions for this and [cypress-plugin-init](https://github.com/elaichenkov/cypress-plugin-init) is one of them.

@kien-ht  thanks for the fast reply and further investigation. I implemented the cypress-plugin-init solution. I will close this issue because this fixes my problem. Thank you!
