### ISSUE TITLE
Incorrect Difference Percentage Resulting from compareSnapshot Command

### ISSUE THREAD

**Issue by palmera01** [uktrade/cypress-image-diff#184]
I was looking into the difference percentages and I noticed that they are different from what I expected them to be. Here are a few screenshots from a report where I created baseline images with a specified percent of pixels different between the two images and compared them. The title of each screenshot has the percentage of pixels different between the created baseline image and the image taken in the compareSnapshot command:
![image](https://github.com/uktrade/cypress-image-diff/assets/147175449/384e9c49-0702-4069-8028-9e467051fb3f)
![image](https://github.com/uktrade/cypress-image-diff/assets/147175449/2a8eb6c7-f1e6-4262-beb2-d192a2f61451)
![image](https://github.com/uktrade/cypress-image-diff/assets/147175449/bc9ff5a5-c2ec-4fac-a074-f08d22d953e8)
![image](https://github.com/uktrade/cypress-image-diff/assets/147175449/25a5deb1-e227-4e46-9224-7121aadc0399)

 I believe this difference is coming from the fact that the difference percentage is square rooted when I don't believe it should be. Is this the expected behavior and I am misunderstanding the percentage value or is this a bug in the package? I saw this behavior on both 1.26.0 and 1.30.1. Thanks!

**Comment by tamasmagyar** [comment]
Any insights, @PippoRaimondi?

**Comment by tamasmagyar** [comment]
Hi @palmera01 

Thanks for raising the question. Based on the provided info it looks like it is incorrect at the moment.

We are currently working on a newer version of the report. Hopeful that's going to fix the issue. 
Let's keep the issue open until we are sure.

**Comment by tamasmagyar** [comment]
Keeping the issue open until v2.0.0
