### ISSUE TITLE
v1.31.0 was a breaking change

### ISSUE THREAD

**Issue by genepaul** [uktrade/cypress-image-diff#186]
https://github.com/uktrade/cypress-image-diff/releases/tag/v1.31.0

As listed in the release notes, the change to "support" ts files was a breaking change, because it now changes the names of the generated files. This was released as a minor version, which is supposed to communicate that it was backwards-compatible. Please release a revert version and re-release this as v2.0.0.

**Comment by genepaul** [comment]
Also, keep in mind that using `js` and `ts` does not allow people to name their files with `jsx` and `tsx`. You end up with baseline images named `test-name.specx`

Honestly, I was fine with the extension being in the image name (`test-name.spec.tsx-Scenario-Name`). Not sure why you even bother replacing at all.

**Comment by PippoRaimondi** [comment]
Thanks for the feedback, it does seem a very low value change, and if it's causing more troubles than help, it's an easy revert... we are looking to release 2.0 of this plugin which will include a few breaking changes, and will move any file naming convention changes there...

**Comment by PippoRaimondi** [comment]
This has now been reverted.
