### ISSUE TITLE
Config "FAILURE_THRESHOLD" did not work

### ISSUE THREAD

**Issue by Strezzo06** [uktrade/cypress-image-diff#200]
Now i use version 2.1.3
Cypress v13.0.0

FAILURE_THRESHOLD: 0.1
<img width="553" alt="Screen Shot 2023-12-26 at 1 08 03 PM" src="https://github.com/uktrade/cypress-image-diff/assets/60592070/e6c5ae10-cd79-4977-ae21-bbf23db43c9d">

Result
<img width="692" alt="Screen Shot 2023-12-26 at 1 07 29 PM" src="https://github.com/uktrade/cypress-image-diff/assets/60592070/d94bbf13-dfa7-4c4a-89b8-d58283b84b70">

I try to add other config
<img width="553" alt="Screen Shot 2023-12-26 at 1 09 04 PM" src="https://github.com/uktrade/cypress-image-diff/assets/60592070/681e50c6-203c-4df9-a892-0cc0173a9af0">

It's working
<img width="249" alt="Screen Shot 2023-12-26 at 1 09 34 PM" src="https://github.com/uktrade/cypress-image-diff/assets/60592070/afad6541-21ad-4d33-95f5-6cfcb904a1e9">

**Comment by tamasmagyar** [comment]
I was **not** able to repro with:

- Cypress `13.1.0` or above _(unfortunately I had issues with 13.0.0)_
- `cypress-image-diff-js 2.1.3`


Config file (`cypress-image-diff.config.cjs`):

```
const config = {
  ROOT_DIR: '',
  FAILURE_THRESHOLD: 0.07,
  COMPARISON_OPTIONS: { threshold: 0.2 },
  RETRY_OPTIONS: {
    log: true,
    limit: 3,
    timeout: 1000,
    delay: 1000
  },
  JSON_REPORT: {
    OVERWRITE: true,
  }
};
module.exports = config;

```

Result:
![image](https://github.com/uktrade/cypress-image-diff/assets/20069588/efad9adc-bb6b-49fd-8511-5171788d3310)

----------------------------------------------------------------------------------------------------------------------------------------------

@Strezzo06 
Can you share the smallest amount of code that reproduces the bug? This helps in isolating the specific problem without the complexity of a larger codebase.


I created an initial project which you can configure to repro the bug, thank you in advance for the help!
Playground repository: https://github.com/tamasmagyar/cypress-image-diff-repro

**Comment by Strezzo06** [comment]
My config file 
`// cypress-image-diff.config.cjs
const config = {
	ROOT_DIR: '',
	FAILURE_THRESHOLD: 0.1,
	COMPARISON_OPTIONS: { threshold: 0.2 }, // default to { threshold: 0.1 }
	RETRY_OPTIONS: {
		log: true,
		limit: 3, // max number of iterations
		timeout: 15000, // time limit in ms
		delay: 1000, // delay before next iteration, ms
	},
	JSON_REPORT: {
		// FILENAME: 'cypress_visual_report', // default "report_[datetime].json"
		OVERWRITE: true, // default true
	},
};
module.exports = config;
`

cypress.config.js
`const { defineConfig } = require('cypress');
const getCompareSnapshotsPlugin = require('cypress-image-diff-js/plugin');

module.exports = defineConfig({
	defaultCommandTimeout: 15000,
	viewportWidth: 1440,
	viewportHeight: 900,
	waitForAnimations: true,
	scrollBehavior: 'center',
	e2e: {
		setupNodeEvents(on, config) {
			// // import and initialise the cypress image diff plugin
			getCompareSnapshotsPlugin(on, config);

			//Separate CV/LCV
			if (config.env.WEB === 'lcv') {
				return {
					specPattern: ['cypress/e2e/lcv/**/product*.cy.js'],
				};
			} else if (config.env.WEB === 'cv') {
				return {
					specPattern: ['cypress/e2e/cv/**/*.cy.js'],
				};
			}
			return getCompareSnapshotsPlugin(on, config);
		},
		baseUrl: 'http://localhost:3000',
		specPattern: 'cypress/e2e/**/*.{js,jsx,ts,tsx}',
	},
});
`
I will try to run on cypress 13.6.1 to compare with cypress 13.0.0

**Comment by Strezzo06** [comment]
I found the root cause. My problem is this line before return config
```
//Separate CV/LCV
			if (config.env.WEB === 'lcv') {
				return {
					specPattern: ['cypress/e2e/lcv/**/product*.cy.js'],
				};
			} else if (config.env.WEB === 'cv') {
				return {
					specPattern: ['cypress/e2e/cv/**/*.cy.js'],
				};
			}
```

When i remove this line. My config can work properly.
<img width="1068" alt="Screen Shot 2023-12-27 at 2 27 09 PM" src="https://github.com/uktrade/cypress-image-diff/assets/60592070/64120a89-3a00-4834-ba72-1e160ac42d6d">

**Comment by tamasmagyar** [comment]
Can you try the following changes, please?
```

const { defineConfig } = require('cypress');
const getCompareSnapshotsPlugin = require('cypress-image-diff-js/plugin');

module.exports = defineConfig({
	defaultCommandTimeout: 15000,
	viewportWidth: 1440,
	viewportHeight: 900,
	waitForAnimations: true,
	scrollBehavior: 'center',
	e2e: {
		setupNodeEvents(on, config) {
			//Separate CV/LCV
			if (config.env.WEB === 'lcv') {
                                config.specPattern = 'cypress/e2e/lcv/**/product*.cy.js'
			} else if (config.env.WEB === 'cv') {
				config.specPattern = 'cypress/e2e/cv/**/*.cy.js'
			}
			return getCompareSnapshotsPlugin(on, config);
		},
		baseUrl: 'http://localhost:3000',
		specPattern: 'cypress/e2e/**/*.{js,jsx,ts,tsx}',
	},
});
```

**Comment by Strezzo06** [comment]
> Can you try the following changes, please?
> 
> I think assigning to `config.specPattern` should do job, you don't have to return with that.
> 
> ```
> const { defineConfig } = require('cypress');
> const getCompareSnapshotsPlugin = require('cypress-image-diff-js/plugin');
> 
> module.exports = defineConfig({
> 	defaultCommandTimeout: 15000,
> 	viewportWidth: 1440,
> 	viewportHeight: 900,
> 	waitForAnimations: true,
> 	scrollBehavior: 'center',
> 	e2e: {
> 		setupNodeEvents(on, config) {
> 			//Separate CV/LCV
> 			if (config.env.WEB === 'lcv') {
>                                 config.specPattern = 'cypress/e2e/lcv/**/product*.cy.js'
> 			} else if (config.env.WEB === 'cv') {
> 				config.specPattern = 'cypress/e2e/cv/**/*.cy.js'
> 			}
> 			return getCompareSnapshotsPlugin(on, config);
> 		},
> 		baseUrl: 'http://localhost:3000',
> 		specPattern: 'cypress/e2e/**/*.{js,jsx,ts,tsx}',
> 	},
> });
> ```

Thank you so much, it's work.
