### ISSUE TITLE
Missing JSON report when in `cypress OPEN` mode

### ISSUE THREAD

**Issue by nanocreaator** [uktrade/cypress-image-diff#204]
⚠️ Please, ignore if that is an expected behavior.

We noticed that when run in interface/UI mode:
```ts
cypress open 
```
the JSON report is not automatically generated.

However, when ran as headless mode:
```ts
cypress run
```
it works as expected.

We tested that using you example/template with TS.

**Comment by PippoRaimondi** [comment]
This plugin was never intended to be used on the `open` mode...

reason why is that tests need to be consistently ran in the same machinery, if the same test runs in 2 different mac specs, you will get unwanted image differences...

**Comment by hsoulier** [comment]
Thanks a lot for your response !

**Comment by nanocreaator** [comment]
Hey Pippo!
Ok, got it!
We couldn't find that info on docs.
Thanks for your prompt answer!
