### ISSUE TITLE
Error: ERR_PACKAGE_PATH_NOT_EXPORTED

### ISSUE THREAD

**Issue by nikitalepikhin-ext54869** [uktrade/cypress-image-diff#210]
I have set cypress component tests up for a React TS application in a NX monorepo. The contents of the `cypress.config.ts` file are the following:

```
import { defineConfig } from 'cypress';
import { nxComponentTestingPreset } from '@nx/react/plugins/component-testing';
import getCompareSnapshotsPlugin from 'cypress-image-diff-js/types/plugin';

export default defineConfig({
  component: {
    ...nxComponentTestingPreset(__filename, {
      bundler: 'webpack',
    }),
    setupNodeEvents(on, config) {
      return getCompareSnapshotsPlugin(on, config);
    },
  },
});
```

Upon launching cypress tests, I am getting the following error: `Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './types/plugin' is not defined by "exports" in /Users/myUsername/.../node_modules/cypress-image-diff-js/package.json`.

These are the versions of packages from `package.json`:

```
"cypress": "12.2.0",
"cypress-image-diff-html-report": "2.0.2",
"cypress-image-diff-js": "2.1.3",
```

What could be causing this issue here? Thank you.

**Comment by vijaycapsifi** [comment]
Even with `import getCompareSnapshotsPlugin from 'cypress-image-diff-js/types/plugin';` there is an error

TS2307: Cannot find module 'cypress-image-diff-js/plugin' or its corresponding type declarations.

**Comment by kien-ht** [comment]
@vijaycapsifi As Timduffin suggested above, it should be:

```
import getCompareSnapshotsPlugin from 'cypress-image-diff-js/plugin';
```
Please refer to our [documentation](https://cypress.visual-image-diff.dev/getting-started/cypress-integration/typescript) for further details
