### ISSUE TITLE
I am not able to find cy.compareSnapshot command.

### ISSUE THREAD

**Issue by ohmygar1989** [uktrade/cypress-image-diff#23]
I have follow the steps not able to find this function.. Please help.

The error is saying property compareSnapshot does not exist on type cy.

// cypress/support/commands.js
const compareSnapshotCommand = require('cypress-image-diff-js/dist/command')
compareSnapshotCommand()

// cypress/support/index.js
require('./commands')

//plugins/indes.js
const cucumber = require('cypress-cucumber-preprocessor').default
const browserify = require('@cypress/browserify-preprocessor');
const resolve = require('resolve');
const getCompareSnapshotsPlugin = require('cypress-image-diff-js/dist/plugin')
module.exports = (on, config) => {
  const options = {
    ...browserify.defaultOptions,
    typescript: resolve.sync('typescript', { baseDir: config.projectRoot }),
  };

  on('file:preprocessor', cucumber(options));
  getCompareSnapshotsPlugin(on, config)
};

What is wrong with my settings? Thanks.

**Comment by PippoRaimondi** [comment]
yes, add the below to `plugin/index.js`:

```
const compareSnapshotCommand = require('cypress-image-diff-js/dist/command')
compareSnapshotCommand()
```

so it will look like:

```
const cucumber = require('cypress-cucumber-preprocessor').default
const browserify = require('@cypress/browserify-preprocessor');
const resolve = require('resolve');
const getCompareSnapshotsPlugin = require('cypress-image-diff-js/dist/plugin')
module.exports = (on, config) => {
const options = {
...browserify.defaultOptions,
typescript: resolve.sync('typescript', { baseDir: config.projectRoot }),
};

on('file:preprocessor', cucumber(options));
const compareSnapshotCommand = require('cypress-image-diff-js/dist/command')
compareSnapshotCommand()
};
```

**Comment by ohmygar1989** [comment]
![image](https://user-images.githubusercontent.com/22483242/104865019-abaf5a00-599f-11eb-9769-226079078ab9.png)
Thanks for your information! But I still cannot find the command after using your setting. :(

**Comment by PippoRaimondi** [comment]
I just realised you have the wrong imports happening... please follow the documentation below carefully:

https://github.com/uktrade/cypress-image-diff/blob/main/docs/Cypress%20integration.md

It's proven to work with cucumber setup so this is a setup issue in your end. I will be closing this issue shortly.

**Comment by PippoRaimondi** [comment]
This is a setup issue.

**Comment by IndBar** [comment]
solved this by using a different location: instead of `cypress-image-diff-js/dist/command`, I used `cypress-image-diff-js/command`  .
 
commnds.js file
```
const compareSnapshotCommand = require('cypress-image-diff-js/command');
compareSnapshotCommand();
```

cypress.config.js
`const getCompareSnapshotsPlugin = require('cypress-image-diff-js/plugin');`
```
    setupNodeEvents(on, config) {
      require('./cypress/plugins/index.js')(on, config);
      cypressSplit(on, config);
      getCompareSnapshotsPlugin(on, config)
      return config;
    },
```

**Comment by Loic-Jhs** [comment]
Solved this like @IndBar fix, but in my case I just set the import like this in my command.ts file : 

```typescript
//command.ts

/// <reference types="cypress" />
import compareSnapshotCommand from "cypress-image-diff-js";
compareSnapshotCommand();
```

``` typescript
//cypress.config.ts

import { defineConfig } from "cypress";
import getCompareSnapshotsPlugin from "cypress-image-diff-js/plugin";

export default defineConfig({
  e2e: {
    baseUrl: "http://localhost:5173",
    setupNodeEvents(on, config) {
      // implement node event listeners here
      return getCompareSnapshotsPlugin(on, config);
    },
  },
});
```
