### ISSUE TITLE
I can't get failed Cypress screenshots

### ISSUE THREAD

**Issue by jradom** [uktrade/cypress-image-diff#28]
Hello,

Once I've started to use your tool it looks like it suppresses failed screenshot generation.  Is it a way to still keep failed screenshots to be generated?

Thanks

Jeff

**Comment by PippoRaimondi** [comment]
What version of the tool are you using? Ensure to use the latest.

Also as good practice you should keep visual and functional test suites separate...

**Comment by jradom** [comment]
Hi Pippo,

I use 1.9.0 and discovered that failed screenshots are
suppressed recently.  When I comment out your plugin in the code they come
back.  Unfortunately, I can't have a separate project for Visual tests.
But I do like your tool a lot.  Please, help

Thanks

Jeff

**Comment by PippoRaimondi** [comment]
should be solved by #30
