### ISSUE TITLE
Support Cypress 7

### ISSUE THREAD

**Issue by skydever** [uktrade/cypress-image-diff#33]
Hi!

First of all, thx for this project! 👍 

I am using Cypress version 7 (`7.6.0`) and everytime I run `npm install` two versions of cypress will be installed - `7.6.0` and `6.9.1`. I think that [this](https://github.com/uktrade/cypress-image-diff/blob/main/package.json#L44) line is the issue - you are referencing `"cypress": "^6.1.0"` at `package.json`.

Do you plan on updating this to `"cypress": "^7.0.0"` (or remove the hard dep. at all)?
It seems that the project is working correctly with version 7 (I run `cypress cache prune` after `npm install` to only have version `7.6.0` installed).

Another thing - I am using `1.10.3` of this library, because the latest release including `npm-force-resolutions` broke my project (fresh `npm ci` brings an error `package-lock.json` not found) - and I would be happy if you would not use that at all. Can you remove it - or why is it required?

Thank you in advance!

**Comment by PippoRaimondi** [comment]
@skydever `1.11.1` now supports cypress `7.6.0` and `npm resolution` should no longer be a problem. Closing this issue.

**Comment by skydever** [comment]
@PippoRaimondi thx a lot!
