### ISSUE TITLE
file copy error after test due to use of > char

### ISSUE THREAD

**Issue by lvxwrkr777** [uktrade/cypress-image-diff#47]
`Error: ENOENT: no such file or directory, copyfile 'C:\repos\cypress\screenshots\503.spec.ts\503.spec.ts-#main  article.png' -> 'C:\repos\cypress-visual-screenshots\comparison\503.spec.ts-#main > article.png'`

The > char is a bad character in Windows filesystem.

**Comment by PippoRaimondi** [comment]
This issue has been fixed in previous merged PRs
