### ISSUE TITLE
Bug: Expected viewportHeight to be a number -error after upgrading cypress version to 9.0.0

### ISSUE THREAD

**Issue by dhamo-pk** [uktrade/cypress-image-diff#50]
It was working perfectly fine with cypress version 8.7.0 and this package with version 1.14.4. I upgraded cypress to 9.0.0 and then I started to get the following error in the test runner. 

Also, I upgraded "cypress-image-diff-js": "^1.15.5", but the error is still same. 

The error:

```
The following error originated from your test code, not from Cypress.

  > Expected viewportHeight to be a number. Instead the value was: "1440"

When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.

Cypress could not associate this error to any specific test.
```

& the cypress.json:

```
  "viewportWidth": 1440,
  "viewportHeight": 900,
```

Screenshot:
![image](https://user-images.githubusercontent.com/44419390/141284270-35854fe1-2efd-420d-a6f8-5a3f90acfe3b.png)

**Comment by PippoRaimondi** [comment]
ok, I am checking!

**Comment by PippoRaimondi** [comment]
I apologise, I was on vacation... I've made the fix a bit more robust so this doesn't happen again...

**Comment by PippoRaimondi** [comment]
@dhamo-pk I am closing this issue. thanks for raising it and the PR as well.

**Comment by dhamo-pk** [comment]
Excellent, thank you @PippoRaimondi
