### ISSUE TITLE
Recently started to see  run-time isue while running on Jenkins

### ISSUE THREAD

**Issue by jradom** [uktrade/cypress-image-diff#54]
![image](https://user-images.githubusercontent.com/20550461/143338055-896356fd-5fde-4838-a2a2-550c20b389eb.png)
Please, help

Thanks

Jeff

**Comment by PippoRaimondi** [comment]
Will have a look this weekend or Monday given I am on the road.

**Comment by jradom** [comment]
Will be great. 

Thanks a lot in advance 

Jeff

**Comment by PippoRaimondi** [comment]
Couldn't replicate, closing this issue.
