### ISSUE TITLE
cy.task('rp_screenshot') failed with the following error:

### ISSUE THREAD

**Issue by lasithdilshan20** [uktrade/cypress-image-diff#60]
Hi,

I just got the following error after executing the basic test with this plug-in.

Script

`describe('Visuals', () => {
    it('should compare screenshot of the entire page', () => {
        cy.visit('www.google.com')
        cy.compareSnapshot('home-page')
    })
})`

Error - 

`CypressError
cy.task('rp_screenshot') failed with the following error:

The task 'rp_screenshot' was not handled in the plugins file. The following tasks are registered: compareSnapshotsPlugin, copyScreenshot, generateReport

Fix this in your plugins file here:
C:\Users\l.wijenayake\OneDrive - ISM eGroup\Workspace\Cypress SCC\Cypress_Test_Automation_React\cypress\plugins\index.jsLearn more`

**Comment by PippoRaimondi** [comment]
Seems to be a none issue, closing.
