### ISSUE TITLE
[Feature Request] Retry Logic

### ISSUE THREAD

**Issue by narinluangrath** [uktrade/cypress-image-diff#62]
The majority of my false positives could be solved by adding some retry logic to the plugin. It would work something like this:

1. If a baseline doesn't exist or `--update` cli arg passed, don't retry (nothing to compare).
2. If a baseline does exist and the test passes, don't retry (already passed).
3. If a baseline does exist and the test fails, retry the snapshot after T milliseconds.
      3a. If the retry passes, continue.
      3b. If the retry fails, try again until N retries have been completed
      3c. If all the retries fail, use the try with the smallest percentage difference to the baseline for the comparison image and error log

Ideally, T and N would be configurable, with default values of 1000 and 3, respectively. 

This feature would also be somewhat idiomatic since [Cypress has retry logic](https://docs.cypress.io/guides/core-concepts/retry-ability#Commands-vs-assertions) built into most assertions.

**Comment by PippoRaimondi** [comment]
This is a good suggestion... I can work on it but end of year is crazy... so I am looking to pick this up mid/late jan... Unless someone else picks it up!

**Comment by narinluangrath** [comment]
Looks like this can be easily implemented using [cypress-recurse](https://github.com/bahmutov/cypress-recurse).
