### ISSUE TITLE
EPERM: operation not permitted, stat

### ISSUE THREAD

**Issue by konstantinschuette** [uktrade/cypress-image-diff#69]
Sometimes when I rerun my tests I get this error:
```
EPERM: operation not permitted, stat 'Z:\nidatracker\apps\nida-divi-e2e\cypress-visual-screenshots\comparison\section1.spec.ts-section1AllDataFilled.png'
```

```
at renameAndMoveFile (Z:\nidatracker\node_modules\cypress-image-diff-js\dist\utils.js:60:23)
    at Object.handler (Z:\nidatracker\node_modules\cypress-image-diff-js\dist\plugin.js:170:34)
```

plugin.js (the second last line failed):
```
on('after:screenshot', function (details) {
    // Change screenshots file permission so it can be moved from drive to drive
    (0, _utils.setFilePermission)(details.path, 511);
    (0, _utils.renameAndMoveFile)(details.path, _config["default"].image.comparison(details.name));
  });
```

utils.js (the second line failed):
```
var renameAndMoveFile = function renameAndMoveFile(originalFilePath, newFilePath) {
  _fsExtra["default"].moveSync(originalFilePath, newFilePath, {
    overwrite: true
  });
};
```

Has anybody faced this issue?

------------

After some research, it seems like setting the permission is what causes this problem.
Because when an image already exists in `cypress-visual-screenshots/comparison` a permission gets applied and it cannot be overwritten.

The workaround would be deleting the images in `cypress-visual-screenshots/comparison` after each test...

**Comment by PippoRaimondi** [comment]
I will be having a look at this.

**Comment by bentleyvk** [comment]
I am having the same issue. If I understand correctly it appears only when running Docker Desktop with WSL flag enabled:
![image](https://user-images.githubusercontent.com/36186912/156986253-1b81a9fd-acd6-43a4-9e48-0fcb2fd6ceed.png)
Because disabling this flag, tests passes.
Also, when I commented out `(0, _utils.setFilePermission)(details.path, 511);`, tests pass even with this flag on.
Here is more info about WSL and file permissions: https://docs.docker.com/desktop/windows/troubleshoot/#permissions-errors-on-data-directories-for-shared-volumes
Just curious why it is needed to change permissions to `511`?

**Comment by PippoRaimondi** [comment]
@bentleyvk we change the permission of the screenshot so the file can be copied/removed from one folder to the other. I think similar to this issue, there is some confiugration that will fail if we don't set the permission. I think if we copy only instead file permission is not necessary.

**Comment by KimBum** [comment]
The changelogs

> > @bentleyvk we change the permission of the screenshot so the file can be copied/removed from one folder to the other. I think similar to this issue, there is some confiugration that will fail if we don't set the permission. I think if we copy only instead file permission is not necessary.
> 
> Do you have any plan of fixing this or any permanent workaround? I have to stay at 1.15.7 due to this issue.
The changes in 1.15.8 do indeed look suspiciously like they could cause permission issues 🤔

**Comment by PippoRaimondi** [comment]
> > @bentleyvk we change the permission of the screenshot so the file can be copied/removed from one folder to the other. I think similar to this issue, there is some confiugration that will fail if we don't set the permission. I think if we copy only instead file permission is not necessary.
> 
> Do you have any plan of fixing this or any permanent workaround? I have to stay at 1.15.7 due to this issue.

yep, I am working on it! I will ask you guys to test it out for feedback soon though

**Comment by PippoRaimondi** [comment]
Can you guys test this out? I assume the problem is overwriting a permissionless file... so adding permission should workaround it:

https://github.com/uktrade/cypress-image-diff/pull/73

**Comment by bentleyvk** [comment]
I still get the same error `Error: ENOENT: no such file or directory, open '/e2e/demo/cypress-visual-screenshots/comparison/PageLayoutDemo.spec.tsx-basic-3440x1440.png'` 😕

**Comment by PippoRaimondi** [comment]
@bentleyvk can you share more details?

- where are you running the tests? locally, some remote desktop, docker etc..
- which directory the tests are triggered?
- what OS are you working on..

Before I can fix it I need to replicate it...

**Comment by bentleyvk** [comment]
> @bentleyvk can you share more details?
> 
> * where are you running the tests? locally, some remote desktop, docker etc..
> * which directory the tests are triggered?
> * what OS are you working on..
> 
> Before I can fix it I need to replicate it...

I am running locally on Windows 10 Version 20H2 using Docker Desktop with `Use the WSL 2 based engine` enabled (when it is disabled, tests seem to pass but sometimes I get the same permission error).
I have a monorepo with yarn workspaces.
I am starting tests using Node script that runs cypress in docker. Test command is triggered in root directory but scripts run in subrepo.

**Comment by ParsonsProjects** [comment]
Hello, I have had a similar issue when running `cypress open` locally on a windows machine. After some trial and error I narrowed it down to the `setFilePermission` function. It looks like the issue is that after opening and changing the file permissions the file stays open which locks other actions being performed on the given file. 

This is a really quick fix adding `closeSync` to the end of the function to ensure that the file is closed to give other actions access to the files.

```
const setFilePermission = (dir, permission) => {
  try {
    if (fs.existsSync(dir)) {
      const fd = fs.openSync(dir, 'r')
      fs.fchmodSync(fd, permission)
      fs.closeSync(fd)
    }
  } catch (error) {
    // eslint-disable-next-line no-console
    console.log(error)
  }
}
```

**Comment by himbolion** [comment]
I still having this Error as well, I'll try the solution above and report back if it works in my case

**Comment by himbolion** [comment]
Yup, adding that fixes it for me as well
