### ISSUE TITLE
Ability to hide elements of the page

### ISSUE THREAD

**Issue by PippoRaimondi** [uktrade/cypress-image-diff#7]
The intent of this enhancement is to hide elements that are dynamically rendered based on third party services or timestamp, causing visual regression tests to be flaky or increasing complexity to deal with these scenarios.

**Comment by jarretmoses** [comment]
@PippoRaimondi I am guessing you are speaking about something like an `intercom` button rendering. I agree this would be helpful and personally am potentially going to work around this by manipulating the dom. I notice that it's a similar issue to any `fixed` positioned element that gets in the way of the screen shot like the header but these elements get plastered along the entirety of a full page screenshot.

**Comment by PippoRaimondi** [comment]
@jarretmoses completely missed this msg, apologies... I am about to pick this up...

The solution would be hide elements in the dom before taking a screenshot. This would allow you to get rid of any dynamic element that would mess up the result of visual test, making it more flexible and reliable.
