### ISSUE TITLE
cypress-image-diff overrides my cypress.json viewports

### ISSUE THREAD

**Issue by fangmarks** [uktrade/cypress-image-diff#74]
Hello!

I have viewport sizes set in my cypress.json file, and as the Title says, even though I have them defined, this plugin overrides them and makes them bigger than I want them to.

This Issue is rather annoying, especially because there is no cross-platform way to set the Environment Variables and npm cannot find the "HEIGHT" command because it gets wrongly interpretet.

If possible I'd suggest checking the cypress.config before to see if there's things defined in it

**Comment by PippoRaimondi** [comment]
This is absolutely something we will fix... there is an issue opened which will tackle it:

https://github.com/uktrade/cypress-image-diff/issues/68

I will keep this issue opened as well and implement this feature shortly.

**Comment by himbolion** [comment]
Yay and Thanks for the quick Reply!

I thought I checked the issues to see if there already was someone mentioning this, but i guess i missed that one

**Comment by himbolion** [comment]
Yeah, that would explain why it still resets to 1980x1440 when I use cy.compareSnapshot()
![image](https://user-images.githubusercontent.com/20520193/159706744-bdcd3cfe-5307-4efd-bfce-ae0d9816964b.png)
