### ISSUE TITLE
 cy.compareSnapshot is not a function error

### ISSUE THREAD

**Issue by ivanasy** [uktrade/cypress-image-diff#81]
Hello, please check out following issue that I am facing: 

These are my dependencies: 
   "auth0-js": "^9.18.0",
    "chai": "^4.3.4",
    "chai-exclude": "^2.1.0",
    "cypress": "^9.6.0",
    "cypress-image-diff-js": "^1.18.1",
    "eslint": "^8.7.0",
    "fs": "^0.0.1-security",
    "mocha": "^10.0.0",
    "mochawesome": "^7.1.3",
    "prettier": "^1.19.1"

I have 0 vulnerabilities

But running my visual tests I get error:  cy.compareSnapshot is not a function
Simple test: 

  it('Verify that Login page is loading correctly', () => {
    cy.visit('/');
    cy.wait(5000);
    cy.compareSnapshot(`${envName}-${Cypress.currentTest.title}`);
  });

<img width="763" alt="Screenshot 2022-05-03 at 12 02 36" src="https://user-images.githubusercontent.com/34516002/166435716-0085f9ec-b615-4cea-a6f4-904163440d88.png">

**Comment by ivanasy** [comment]
Wrong setup issue. Closing

**Comment by ssauriera** [comment]
We are having the same issue, how do you fixed?

**Comment by miaSlady** [comment]
i have the same issue too, how do you fixed?
