### ISSUE TITLE
Option to have baseline, comparison and diff screenshots all in single side by side view?

### ISSUE THREAD

**Issue by JasonFairchild** [uktrade/cypress-image-diff#83]
Is there a way to have this with this plugin? I've seen it with other approaches, and it seems really visually nice. Sometimes only the diff can be pretty difficult to read. Kinda like this:
![image](https://user-images.githubusercontent.com/56280950/166856830-7c41f750-b597-4837-8839-977f33b2ed35.png)

Vs something like this (this example is probably the simplest using a single file and from cypress-image-snapshot plugin to be clear, but there are potentially a lot of ways to accomplish this I think)
![input-cleared diff](https://user-images.githubusercontent.com/56280950/167088672-7fd1581e-3078-41f8-949a-3fb2332493b0.png)

**Comment by PippoRaimondi** [comment]
yes, that's a good suggestion... we can update the HTML of the report to present it this way... I will wait to see if anyone in the community that is really good with HTML wants to pick this one up, if not I will fix it.

**Comment by JasonFairchild** [comment]
Cool. I might be oversimplifying it, but it seems like this example is just taking the 3 images and concatenating them into a single image, with baseline on the left and new shot on the right and the diff between. Sounds pretty straightforward, but not something I have experience with so far.

**Comment by kien-ht** [comment]
> yes, that's a good suggestion... we can update the HTML of the report to present it this way... I will wait to see if anyone in the community that is really good with HTML wants to pick this one up, if not I will fix it.

As of today, it seems like this issue hasn't been fixed yet. My project is also using this plugin, so I'd love to help.

**Comment by PippoRaimondi** [comment]
Thanks for contributing @kien-ht ... closing this issue after merging the below:

https://github.com/uktrade/cypress-image-diff/pull/90
