### ISSUE TITLE
Question: any plan to move Cypress to peer dependencies?

### ISSUE THREAD

**Issue by lazurey** [uktrade/cypress-image-diff#87]
Hi there,

First of all, thank you for making this fantastic plugin!
Just a small question, I saw Cypress is in the dependency list in `package.json` and the version is specified.
I'd like to ask is there a plan to move it to `peerDependencies`, so users don't need to install two different Cypress versions (v10 and v9 in my case).

Thanks again!

**Comment by PippoRaimondi** [comment]
Will be fixing this now.
