### ISSUE TITLE
Cypress 10 usage

### ISSUE THREAD

**Issue by oguzhantx** [uktrade/cypress-image-diff#89]
is there support or upgrade needed for this to work with cypress 10? Does anyone have an experience with this with cypress 10?

**Comment by faith-berroya** [comment]
Hello @PippoRaimondi I'm very much excited for the Cypress 10 support. Do you have a timeline for this?

**Comment by stephenwil** [comment]
It attempts to download Cypress v9.7.0 as part of this package install?

**Comment by nmkataoka** [comment]
I opened a PR, until then you can use the workaround here: https://github.com/uktrade/cypress-image-diff/issues/59#issuecomment-1240543726
