### ISSUE TITLE
Make test folders configurable

### ISSUE THREAD

**Issue by PippoRaimondi** [uktrade/cypress-image-diff#9]
Both screenshot and report folders are hardcoded. There might be use cases where we would like to have these folder creation configurable to our needs.

**Comment by mehrad-rafigh** [comment]
@PippoRaimondi I would like to take a shot at this

**Comment by PippoRaimondi** [comment]
@mehrad-rafigh someone raised a PR around this, it needs testing... you might want to have a look at it and maybe finalise it on your own PR. If not I will have some bandwidth this week and will sort it out!

**Comment by mehrad-rafigh** [comment]
@PippoRaimondi thanks for letting me know. That PR has not been updated for a few days. Do you think we should ping the author? I have some time during this week.

**Comment by konstantinschuette** [comment]
Have you done some work on this? Because I want to use this repo in the mono repository NX. Therefore I need multiple test folders. One folder for each E2E test application

**Comment by kristofgilicze** [comment]
I would also prefer if I could put it under ./cypress, or anywhere else for that matter.
I have enough top-level folders without.

Willing to pick this up, if no one is active.
Keeping the root level folders default, should not break stuff ?

**Comment by himbolion** [comment]
Very much agree with @kristofgilicze, I'd like to put these folders into the `/cypress` folder as well, we already have enough top-level folders without testing

**Comment by emreSmrt** [comment]
I want to separate the screenshots which are taken via compareSnapshot() the others [cy.screenshot() and screenshotsOnFailures]. 

In the current status, it removes the screenshots on failures and I cannot see them on CypressDashboard.

It can be applied with a minor change in removeAndMoveFile() in dist/utils.js

If you already have a solution, I want to learn

```
var renameAndMoveFile = function renameAndMoveFile(originalFilePath, newFilePath) {
    if(originalFilePath.includes('foo')){
        _fsExtra["default"].moveSync(originalFilePath, newFilePath, {
            overwrite: true
        });
    }
};

```

**Comment by SaulGoode77** [comment]
This would be HUGE for me if someone can add this option!

**Comment by BatyrSeven** [comment]
Any updates on this?
