### ISSUE TITLE
Getting an error cy.task('copyScreenshot') failed with the following error:  > ENOENT: no such file or directory, stat '(pathname)' when trying to run for the first time

### ISSUE THREAD

**Issue by faith-berroya** [uktrade/cypress-image-diff#99]
Hello. I tried to setup our project and added this plugin that uses baseline for visual testing. On my first run, instead of getting an image on my `baseline` folder, I'm getting this error. Did I miss a step? I have the folder in our repository, same path as to which the error is stating.

<img width="416" alt="image" src="https://user-images.githubusercontent.com/101372793/184819815-29cdade9-fe2e-4ddc-a89d-5a4ed21653f6.png">
<img width="264" alt="image" src="https://user-images.githubusercontent.com/101372793/184819908-2755da93-b002-4d08-9d4c-0714c628dc49.png">

cypress.config.js
```
const getCompareSnapshotsPlugin = require('cypress-image-diff-js/dist/plugin')
module.exports = defineConfig({
  e2e: {
    async setupNodeEvents(on, config) {
        getCompareSnapshotsPlugin(on, config);
```

support/command.js
```
const compareSnapshotCommand = require('cypress-image-diff-js/dist/command')
compareSnapshotCommand()
```
support/e2e.js
`require('./commands')`

Script:
```
     assertHeaderAndFooterSnapshots(headingName){
        this.getHeadingHeader(headingName).eq(0)
            .scrollIntoView()
            .compareSnapshot('try', 0.1)
            .should('exist')
        this.getHeadingFooter(headingName).eq(0)
            .scrollIntoView()
            .compareSnapshot('try', 0.1)
            .should('exist')
        }
}
```

I also tried the one below but same result:
    ```
assertHeaderAndFooterSnapshots(headingName){
        this.getHeadingHeader(headingName).eq(0)
            .scrollIntoView()
            .should('exist')
        cy.compareSnapshot('try', 0.1)
        this.getHeadingFooter(headingName).eq(0)
            .scrollIntoView()
            .should('exist')
        cy.compareSnapshot('try', 0.1)
        }
```

**Comment by surajwaits** [comment]
I am also facing the same error...
@PippoRaimondi, Could you please help us with this issue?

**Comment by PippoRaimondi** [comment]
This might have been due to the first Cypress version 10.x issue with windows and the way they handle screenshot folders... this shouldn't be an issue anymore... I will close within a few weeks if no more complaints

**Comment by jaime1702** [comment]
I am also facing the same error...
@PippoRaimondi , Could you please help us with this issue?

**Comment by jradelmo** [comment]
if you using badeball/cypress-cucumber-preprocessor, try add omitAfterScreenshotHandler as true on plugin configuration.

```javascript
await preprocessor.addCucumberPreprocessorPlugin(on, config, {
    omitAfterScreenshotHandler: true,
  }); 
```
